import { currentValue } from './components/controller/generateCurrentValue.component.js'
import { qCurrent, renderQuestionImg } from './components/view/questionDom.component.js'
import {qImg, qSeq, mBtn} from './components/view/dom.component.js'
import * as eventListener from './components/view/eventListeners.component.js'
import * as modal from './components/view/popUpDom.component.js'
import * as matachAnswer from './components/controller/matchAnswer.component.js'
import * as createReviewLetters from './components/controller/createReviewLetters.component.js'
